name: "API Connect product publish"
description: "Publish a product to an API Connect platform"
author: "Jesús Moreno Amor"
inputs:
  productFile:
    description: "Product file to publish"
  managerHost:
    description: "API Connect Manager endpoint"
  managerUsername:
    description: "API Connect Manager username"
  managerPassword:
    description: "API Connect Manager password"
  managerRealm:
    description: "API Connect Manager authentication realm"
  catalog:
    description: "Catalog where the product will be published"
    default: "sandbox"
  organization:
    description: "Provider organization where the catalog is located"
    default: "localtest"
  space:
    description: "If the catalog has spaces activated, select the space to publish the product"
    default: null
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
