version: 1
disable_existing_loggers: false

formatters:
    github:
        format: "::%(levelname)s::%(message)s"
    standard:
        format: "%(asctime)s - [%(levelname)-7s] - %(module)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout
    github:
        class: logging.StreamHandler
        level: DEBUG
        formatter: github
        stream: ext://sys.stdout

root:
    level: NOTSET
    handlers:
        - github
    propogate: yes

loggers:
    api-deploy:
        level: INFO
        handlers:
            - github
        propogate: no

    urllib3:
        level: INFO
        handlers:
            - console
        propogate: no
